FROM nginx:1.19.2

RUN apt update && apt install apache2-utils -y

ARG USERNAME=admin
ARG PASSWORD
RUN mkdir /etc/apache2
RUN htpasswd -c -b /etc/apache2/.htpasswd ${USERNAME} ${PASSWORD}

COPY nginx/nginx.conf /etc/nginx/nginx.conf