version: "3.3"

services:
  msgraphapi:
    image: hemantksingh/msgraphapi:latest
    container_name: msgraphapi
    ports:
      - 80:80
    environment:
      - AZUREAD_TENANT_ID=${AZUREAD_TENANT_ID}
      - AZUREAD_CLIENT_ID=${AZUREAD_CLIENT_ID}
      - AZUREAD_CLIENT_SECRET=${AZUREAD_CLIENT_SECRET}
