version: "3.9"

services:
  nginx: 
    image: hemantksingh/nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - authUsername=admin
        - authPassword=${authPassword}
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      
  msgraphapi:
    image: hemantksingh/msgraphapi:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: msgraphapi
    expose:
      - "4000"
    environment:
      - AZUREAD_TENANT_ID=${AZUREAD_TENANT_ID}
      - AZUREAD_CLIENT_ID=${AZUREAD_CLIENT_ID}
      - AZUREAD_CLIENT_SECRET=${AZUREAD_CLIENT_SECRET}
