version: "3.3"

services:
  haproxy: 
    image: hemantksingh/haproxy:latest
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    container_name: haproxy
    ports:
      - 80:80
      - 1337:1337
      
  msgraphapi1:
    image: hemantksingh/msgraphapi:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: msgraphapi1
    expose:
      - "4000"
    environment:
      - AZUREAD_TENANT_ID=${AZUREAD_TENANT_ID}
      - AZUREAD_CLIENT_ID=${AZUREAD_CLIENT_ID}
      - AZUREAD_CLIENT_SECRET=${AZUREAD_CLIENT_SECRET}

  msgraphapi2:
    image: hemantksingh/msgraphapi:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: msgraphapi2
    expose:
      - "4000"
    environment:
      - AZUREAD_TENANT_ID=${AZUREAD_TENANT_ID}
      - AZUREAD_CLIENT_ID=${AZUREAD_CLIENT_ID}
      - AZUREAD_CLIENT_SECRET=${AZUREAD_CLIENT_SECRET}
